[package]
name = "mdbook-html"
version = "0.5.0-alpha.1"
description = "mdBook HTML renderer"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true

[features]
search = []
