[package]
name = "mdbook-summary"
version = "0.5.0-alpha.1"
description = "Summary parser for mdBook"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
